######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 21 09:55:35 2010
######################################################################

TEMPLATE = lib
CONFIG += dll
TARGET = ssagcamera
DEPENDPATH += .
INCLUDEPATH += .


win32:		DEFINES += SB_WIN_BUILD
macx:		DEFINES += SB_MAC_BUILD
linux-g++:	DEFINES += SB_LINUX_BUILD

# Input
HEADERS += main.h \
           x2camera.h \
           ../../licensedinterfaces/cameradriverinterface.h \
           ../../licensedinterfaces/driverrootinterface.h \
           ../../licensedinterfaces/linkinterface.h \
           ../../licensedinterfaces/deviceinfointerface.h \
           ../../licensedinterfaces/driverinfointerface.h \
           ../../licensedinterfaces/sberrorx.h \
           ../../licensedinterfaces/serxinterface.h \
           ../../licensedinterfaces/theskyxfacadefordriversinterface.h \
           ../../licensedinterfaces/sleeperinterface.h \
           ../../licensedinterfaces/loggerinterface.h \
           ../../licensedinterfaces/basiciniutilinterface.h \
           ../../licensedinterfaces/mutexinterface.h \
           ../../licensedinterfaces/tickcountinterface.h \
           ../../licensedinterfaces/basicstringinterface.h
SOURCES += main.cpp x2camera.cpp
